default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  user: <%= ENV.fetch("POSTGRES_USER") { "cezar" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>

development:
  primary:
    <<: *default
    database: sales_agent_development

test:
  <<: *default
  database: sales_agent_test

production:
  primary:
    <<: *default
    database: sales_agent_production
  cache:
    <<: *default
    database: sales_agent_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sales_agent_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sales_agent_production_cable
    migrations_paths: db/cable_migrate
